### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ktdreyer** [jebeaudet/SunriseSunsetCalculator#3]
Would you please specify a license for your project?

The [MIT License](http://choosealicense.com/licenses/mit/) is a good option.

**Comment by nfischer** [comment]
@jebeaudet I agree that licensing this would be a smart idea. The MIT license is my current favorite. [This site](http://choosealicense.com/) is a great resource for choosing a license. I'd be fine with my contributions being under GPL or Apache as well.

**Comment by jebeaudet** [comment]
MIT is fine with me as well!
