### ISSUE TITLE
link not exist (in documentation)

### ISSUE THREAD

**Issue by gryken2014** [jebeaudet/SunriseSunsetCalculator#5]
Hello,

I notice that link seems not to exist :

http://williams.best.vwh.net/sunrise_sunset_algorithm.htm

**Comment by jebeaudet** [comment]
You're right, it's referenced on so many pages across the internet on top of that, sad to see it go.

Hopefully it was not a copywright concern, the page is still accessible on the [archive.org](http://web.archive.org/web/20161202180207/http://williams.best.vwh.net/sunrise_sunset_algorithm.htm) webpage. I'll update the readme, thx for reporting!
